# Site settings
title: WEB Spring 2016
#email: arielle.hein@colorado.edu
description: Course website for ATLS 2200. Site buit and maintained by Arielle Hein.
baseurl: '/web-spring-16'
# baseurl: ''
# url: "web-spring-16.com" # the base hostname & protocol for your site

# github_username:  coloringchaos

# Build settings
markdown: kramdown
parse_block_html: true
permalink: /:title

# Make redcarpet behave like GitHub Flavored Markdown 
# redcarpet: 
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]